const books = [
  {
    name: "Steve Jobs",
    author: "Walter Issacson",
    image: require("./Books/stevejobs.png"),
    review:
      "SJ A genius book about an incredible mind, yadda yadda blah blah blah lots of gushing and awing because I like books.",
    link: "/Walter Issacson/Steve Jobs",
    stars: 3,
    price: 11.99,
    qty: "40+",
    genre: "",
    sold: "6",
    date: "2006-08-25",
  },
  {
    name: "Go-To-Dinners",
    author: "Ina Garten",
    image: require("./Books/gotodinners.png"),
    review:
      "GTD A genius book about an incredible mind, yadda yadda blah blah blah lots of gushing and awing because I like books.",
    link: "/Ina Garten/Go-To-Dinners",
    stars: 3,
    price: 120.99,
    qty: "40+",
    genre: "",
    sold: "3",
    date: "2020-03-23",
  },
  {
    name: "How Easy is That?",
    author: "Ina Garten",
    image: require("./Books/howeasyisthat.png"),
    review:
      "HET A genius book about an incredible mind, yadda yadda blah blah blah lots of gushing and awing because I like books.",
    link: "/Ina Garten/How Easy is That",
    stars: 3,
    price: 15.99,
    qty: "40+",
    genre: "",
    sold: "23",
    date: "2022-04-11",
  },
  {
    name: "Jane Eyre",
    author: "Charlotte Bronte",
    image: require("./Books/janeeyre.png"),
    review:
      "JE A genius book about an incredible mind, yadda yadda blah blah blah lots of gushing and awing because I like books.",
    link: "/Charlotte Bronte/Jane Eyre",
    stars: 3,
    price: 16.99,
    qty: "40+",
    genre: "",
    sold: "43",
    date: "2016-06-01",
  },

  {
    name: "Steve Jobs",
    author: "Walter Issacson",
    image: require("./Books/stevejobs.png"),
    review:
      "SJ A genius book about an incredible mind, yadda yadda blah blah blah lots of gushing and awing because I like books.",
    link: "/Walter Issacson/Steve Jobs2",
    stars: 3.5,
    price: 12.99,
    qty: "40+",
    genre: "",
    sold: "12",
    date: "2014-11-05",
  },
  {
    name: "Go-To-Dinners",
    author: "Ina Garten",
    image: require("./Books/gotodinners.png"),
    review:
      "GTD A genius book about an incredible mind, yadda yadda blah blah blah lots of gushing and awing because I like books.",
    link: "/Ina Garten/Go-To-Dinners2",
    stars: 3,
    price: 12.99,
    qty: "40+",
    genre: "",
    sold: "12",
    date: "2006-08-25",
  },
  {
    name: "How Easy is That?",
    author: "Ina Garten",
    image: require("./Books/howeasyisthat.png"),
    review:
      "HET A genius book about an incredible mind, yadda yadda blah blah blah lots of gushing and awing because I like books.",
    link: "/Ina Garten/How Easy is That2",
    stars: 3,
    price: 12.99,
    qty: "40+",
    genre: "",
    sold: "56",
    date: "2016-01-19",
  },
  {
    name: "Jane Eyre",
    author: "Charlotte Bronte",
    image: require("./Books/janeeyre.png"),
    review:
      "JE A genius book about an incredible mind, yadda yadda blah blah blah lots of gushing and awing because I like books.",
    link: "/Charlotte Bronte/Jane Eyre2",
    stars: 3,
    price: 1.99,
    qty: "40+",
    genre: "",
    sold: "0",
    date: "2010-10-26",
  },
];

export default books;
